services:
  postgres:
    image: postgres:15-alpine # Using standard image for diagnostics
    container_name: thewell_postgres_db
    environment:
      POSTGRES_DB: "thewell"
      POSTGRES_USER: "thewell_user"
      POSTGRES_PASSWORD: "SuperSecurePwd123!"
    ports:
      - "5432:5432"
    volumes:
      - postgres_thewell_data:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/01-init-database.sql
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
      - ./src/database/permissions-schema.sql:/docker-entrypoint-initdb.d/03-permissions-schema.sql
      - ./src/ingestion/schemas/visibility.sql:/docker-entrypoint-initdb.d/04-visibility-schema.sql
      - ./00-create-user.sql:/docker-entrypoint-initdb.d/00-create-user.sql
    restart: unless-stopped

volumes:
  postgres_thewell_data:
