groups:
  - name: thewell-alerts
    rules:
      # Cost alerts
      - alert: HighCostRate
        expr: rate(thewell_cost_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High cost rate detected"
          description: "Cost rate is {{ $value }} USD/minute for {{ $labels.provider }} {{ $labels.model }}"

      - alert: BudgetExceeded
        expr: thewell_budget_utilization > 100
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Budget exceeded"
          description: "Budget {{ $labels.budget_name }} has exceeded 100% utilization ({{ $value }}%)"

      - alert: BudgetWarning
        expr: thewell_budget_utilization > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Budget warning"
          description: "Budget {{ $labels.budget_name }} is at {{ $value }}% utilization"

      # Quality alerts
      - alert: HighAPIResponseTime
        expr: histogram_quantile(0.95, rate(thewell_api_response_time_seconds_bucket[5m])) > 2
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High API response time"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.endpoint }}"

      - alert: CriticalAPIResponseTime
        expr: histogram_quantile(0.95, rate(thewell_api_response_time_seconds_bucket[5m])) > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Critical API response time"
          description: "95th percentile response time is {{ $value }}s for {{ $labels.endpoint }}"

      - alert: HighErrorRate
        expr: thewell_error_rate > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}% for {{ $labels.service }} {{ $labels.endpoint }}"

      - alert: SLOViolation
        expr: thewell_slo_compliance < 95
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "SLO compliance violation"
          description: "SLO {{ $labels.slo_name }} is at {{ $value }}% compliance"

      - alert: CriticalSLOViolation
        expr: thewell_slo_compliance < 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Critical SLO compliance violation"
          description: "SLO {{ $labels.slo_name }} is at {{ $value }}% compliance"

      # System alerts
      - alert: LowCacheHitRate
        expr: thewell_cache_hit_rate < 70
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate for {{ $labels.cache_type }} is {{ $value }}%"

      - alert: LargeQueueSize
        expr: thewell_queue_size > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Large queue size"
          description: "Queue {{ $labels.queue_name }} has {{ $value }} items"

      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "Service {{ $labels.job }} is down"

      # Document processing alerts
      - alert: SlowDocumentProcessing
        expr: histogram_quantile(0.95, rate(thewell_document_processing_time_seconds_bucket[5m])) > 60
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Slow document processing"
          description: "95th percentile processing time is {{ $value }}s for {{ $labels.strategy }}"

      - alert: LowIngestionRate
        expr: rate(thewell_documents_ingested_total[5m]) < 0.1
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low document ingestion rate"
          description: "Document ingestion rate for {{ $labels.source_type }} is {{ $value }} docs/minute"