name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        echo "Image: ghcr.io/${{ github.repository }}:${{ github.sha }}"
        # Add actual deployment commands here (e.g., kubectl, docker-compose, etc.)
    
    - name: Health check
      run: |
        echo "Performing health check..."
        # Add health check commands here
        # curl -f http://staging.thewell.example.com/health || exit 1
    
    - name: Notify deployment
      if: always()
      run: |
        echo "Deployment status: ${{ job.status }}"
        # Add notification logic here (Slack, email, etc.)

  deploy-production:
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    runs-on: ubuntu-latest
    environment: production
    needs: []  # Add staging deployment as dependency when ready
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:production
          ghcr.io/${{ github.repository }}:prod-${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Deploy to production
      run: |
        echo "Deploying to production environment..."
        echo "Image: ghcr.io/${{ github.repository }}:prod-${{ github.sha }}"
        # Add actual deployment commands here
    
    - name: Health check
      run: |
        echo "Performing production health check..."
        # Add production health check commands here
        # curl -f http://thewell.example.com/health || exit 1
    
    - name: Notify deployment
      if: always()
      run: |
        echo "Production deployment status: ${{ job.status }}"
        # Add notification logic here
